name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy images
        run: mkdir build && cp -R img build/img

      - name: Marp Build (webpage)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: 37C3_lightningtalk_h책ck-mas-castle.md -o build/index.html
        env:
          MARP_USER: root:root

      # - name: Marp Build (37C3_lightningtalk_h책ck-mas-castle.pdf)
      #   uses: docker://marpteam/marp-cli:v3.4.0
      #   with:
      #     args: 37C3_lightningtalk_h책ck-mas-castle.md --pdf --allow-local-files -o build/37C3_lightningtalk_h책ck-mas-castle.pdf
      #   env:
      #     MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
